# Generated by Django 4.2.17 on 2025-01-13 11:56

import django.contrib.auth.password_validation
import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('last_login',
                 models.DateTimeField(
                     blank=True,
                     null=True,
                     verbose_name='last login')),
                ('is_superuser',
                 models.BooleanField(
                     default=False,
                     help_text='Designates that this user has all permissions without explicitly assigning them.',
                     verbose_name='superuser status')),
                ('username',
                 models.CharField(
                     error_messages={
                         'unique': 'A user with that username already exists.'},
                     help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                     max_length=150,
                     unique=True,
                     validators=[
                         django.contrib.auth.validators.UnicodeUsernameValidator()],
                     verbose_name='username')),
                ('password',
                 models.CharField(
                     max_length=128,
                     null=True,
                     validators=[
                         django.contrib.auth.password_validation.validate_password],
                     verbose_name='password')),
                ('is_active',
                 models.BooleanField(
                     default=True,
                     help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                     verbose_name='active')),
                ('is_staff',
                 models.BooleanField(
                     default=True,
                     help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                     verbose_name='staff')),
                ('force_change_pass',
                 models.BooleanField(
                     default=True,
                     verbose_name='force change password')),
                ('date_joined',
                 models.DateTimeField(
                     auto_now_add=True,
                     verbose_name='date joined')),
                ('first_name',
                 models.CharField(
                     max_length=150,
                     null=True,
                     verbose_name='first name')),
                ('last_name',
                 models.CharField(
                     max_length=150,
                     null=True,
                     verbose_name='last name')),
                ('avatar',
                 models.ImageField(
                     null=True,
                     storage=utils.storage.ImageStorage(),
                     upload_to='avatars/',
                     verbose_name='avatar')),
                ('groups',
                 models.ManyToManyField(
                     blank=True,
                     help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                     related_name='user_set',
                     related_query_name='user',
                     to='auth.group',
                     verbose_name='groups')),
                ('user_permissions',
                 models.ManyToManyField(
                     blank=True,
                     help_text='Specific permissions for this user.',
                     related_name='user_set',
                     related_query_name='user',
                     to='auth.permission',
                     verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordRecord',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('password',
                 models.CharField(
                     editable=False,
                     max_length=128,
                     verbose_name='password hash')),
                ('date',
                 models.DateTimeField(
                     auto_now_add=True,
                     verbose_name='date')),
                ('user',
                 models.ForeignKey(
                     editable=False,
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='password_records',
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
    ]
